### ISSUE TITLE
STM32WL: In DualCore Firmware CM0PLUS binary size is too large

### ISSUE THREAD

**Issue by PG430** [STMicroelectronics/STM32CubeWL#13]
Hello,

STM32WL dual core is using M0+ and M4. GIT release v1.0.0 has firmware for both.
but when we compiled the M0+ "LoRaWAN_End_Node_DualCore" source binary size is unexpectedly too large 
Bin size: 393126Kb 
ELF size: 2588Kb
Hex size: 196Kb

![image](https://user-images.githubusercontent.com/55126032/120760824-2da8b580-c532-11eb-9750-bbec903e881c.png)

Now to reduce the size of binary i've made changes in .ld file,

![image](https://user-images.githubusercontent.com/55126032/120761116-7a8c8c00-c532-11eb-88f0-1c4be959163f.png)

after .ld file change, binary size is reduced in KB

![image](https://user-images.githubusercontent.com/55126032/120761271-a445b300-c532-11eb-860e-4589430ff714.png)

**Comment by PG430** [comment]
Thank you for accepting this problem,

Is there any fix for this issue?

**Comment by ASELSTM** [comment]
Hi @PG430,

Thank you for you contribution.

Please allow me to introduce @YoannBo who will comment your post and provide you with more details about this point.

With regards,

**Comment by YoannBo** [comment]
Hi @PG430,

You are right. This is implemented in the upcoming release (coming very soon),

thank you

**Comment by PG430** [comment]
@YoannBo Thank you for the confirmation
