### ISSUE TITLE
lora_app.c: Wrong logic operator in sanity check in OnRxData function.

### ISSUE THREAD

**Issue by Braindawgs** [STMicroelectronics/STM32CubeWL#28]
Sanity check in `OnRxData` function uses the wrong logic operator, should be `&&` + `AppData` has a `Buffer`, pointer member in the struct which can be NULL, and it is not checked. 

```c
static void OnRxData(LmHandlerAppData_t *appData, LmHandlerRxParams_t *params)
{
  /* USER CODE BEGIN OnRxData_1 */
  if ((appData != NULL) || (params != NULL))
  ....
```
[Line](https://github.com/STMicroelectronics/STM32CubeWL/blob/main/Projects/NUCLEO-WL55JC/Applications/LoRaWAN/LoRaWAN_End_Node/LoRaWAN/App/lora_app.c#L330)

**Comment by ASELSTM** [comment]
ST Internal Reference: 117554
