### ISSUE TITLE
Incorrect address offsets for ITM

### ISSUE THREAD

**Issue by gbThreepwood** [STMicroelectronics/STM32CubeWL#40]
According to the reference manual (RM0453) page 1395, we have the following:

* ITM trace enable register (ITM_TER) offset: 0x080
* ITM trace privilege register (ITM_TPR) offset: 0xE00.

As far as I can tell, this does not match the offsets used in the CMSIS header. Not sure if this is an issue with the reference manual, or the header though.

ITM trace control register (ITM_TCR) has an offset which matches the CMSIS. I have not checked the rest of the registers in the ITM.

https://github.com/STMicroelectronics/STM32CubeWL/blob/59c5722deaf51724cff8446413a7a76792d8bb81/Drivers/CMSIS/Core/Include/core_cm4.h#L820

**Comment by ASELSTM** [comment]
Hi @gbThreepwood,


The CMSIS Core files are out of scope of STMicroelectronics as they are provided by ARM. All changes and updates to these files are not managed by our technical team but rather by ARM's team. Therefore, you may report this issue on [ARM](https://github.com/ARM-software) GitHub.

Please allow me then to close this issue and hank you for your contribution.

With regards,
