### ISSUE TITLE
Dead Lock during Retransmissions

### ISSUE THREAD

**Issue by J0hanss0n** [STMicroelectronics/STM32CubeWL#45]
**Set-up**
LSM100A based Evaluation Kit (STM32WL55JC)
STM32CubeIDE Version: 1.10.1
https://github.com/SeongJiIoT/LSM100A_SDK

**Description**
Function RegionCommonUpdateBandTimeOff ([RegionCommon.c](https://github.com/STMicroelectronics/STM32CubeWL/blob/59c5722deaf51724cff8446413a7a76792d8bb81/Middlewares/Third_Party/LoRaWAN/Mac/Region/RegionCommon.c#L350)) can lead to a Dead Lock (at least during retransmissions), if bands[i].TimeCredits == creditCosts because the band[i].ReadyForTransmission is then set to false but a minTimeToWait = 0 is returned.

In ScheduleTx ([LoraMac.c](https://github.com/STMicroelectronics/STM32CubeWL/blob/59c5722deaf51724cff8446413a7a76792d8bb81/Middlewares/Third_Party/LoRaWAN/Mac/LoRaMac.c#L2534)) the MacCtx.DutyCycleWaitTime is checked for != 0 and the timer is then not started.

**Pull Request (just a proposal)**
#44 
As an alternative the timer could be started with a minimal waiting time when MacCtx.DutyCycleWaitTime == 0

**Comment by ASELSTM** [comment]
ST Internal Reference: 134011
