### ISSUE TITLE
How to dual core on the  NucleoWL55JC1 ?

### ISSUE THREAD

**Issue by MrGloriousFast** [STMicroelectronics/STM32CubeWL#62]
Hello,
I downloaded the repository and want to use the "LoRaWAN_End_Node" as a basis to work from with the "STM32CubeIDE" environment.

I have a NucleoWL55JC1 board that has a cm0 and cm4 chip. When i create a new project via the IDE and select my nuccleo board it creates a PROJECTNAME_CM0PLUS and a PROJECTNAME_CM4 folder. each with their own main.c files and while loops.

However if i use the "LoRaWAN_End_Node" example i only get one main file with only one while loop inside. Is the example not for dual core MCU? How can i have two while loops running in parallel? For examlpe one printing "HELLO WORLD1" and the other printing "HELLO WORLD2" ?

**Comment by RJMSTM** [comment]
Hello @avisconti,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With regards,
Rania

**Comment by niclash** [comment]
You also have
     Projects/NUCLEO-WL55JC/Applications/LoRaWAN/LoRaWAN_End_Node_DualCore
     Projects/NUCLEO-WL55JC/Applications/LoRaWAN/LoRaWAN_End_Node_DualCoreFreeRTOS

as examples and has the setup that you are expecting.

**Comment by negotiate-merge** [comment]
@MrGloriousFast I have had the same struggles that you are experiencing and have found these two resources to be of great benefit:

**STM32CubeIDE dual core project on STM32WL55**
https://www.st.com/content/st_com/en/support/learning/stm32-education/stm32-moocs/STM32CubeIDE_dual_core_STM32WL55_MOOC.html

**STM32WL55 IPCC (inter-process communication controller) in practice**
https://www.st.com/content/st_com/en/support/learning/stm32-education/stm32-moocs/stm32wl55-ipcc-mooc.html

**Comment by RJMSTM** [comment]
Hello @avisconti,

Please allow me to close this issue. You may reopen it at any time if you have any details to share with us in order to help you to solve the issue. Thank you for your comprehension.

With Regards,
Rania
