### ISSUE TITLE
LoRaWAN stack upgrade

### ISSUE THREAD

**Issue by pd-vt** [STMicroelectronics/STM32CubeWL#79]
Recently the LoRaWAN Basic modem stack which is parent stack for ST's example code is retired and not recommended to use for new development. https://github.com/Lora-net/SWSD001 and instead its recommended to use the new Stack. https://github.com/Lora-net/SWL2001

What would be the ETA to upgrade STM32CubeWL package with this new stack? because support for mordern LoRaWAN standards like Fragmented Data block Transport for V2.0.0 is not available in previous version of stack.

**Comment by RJMSTM** [comment]
Hello @pd-vt,

Unfortunately, there is no plan to upgrade STM32CubeWL package with the new stack. I will keep you informed if there are any updates.
Please allow me to close this issue.

Thank you in advance for your comprehension.

Best Regards,
