### ISSUE TITLE
SFR and SFD files are missing in Keil pack 

### ISSUE THREAD

**Issue by MaxFlatline** [STMicroelectronics/STM32CubeWL#88]
Hello, since the keil pack is included in this repository, i thought it's ok to ask here. 

**Set-up**

 * Nucleo-WL55JC1
 * Keil Uvision 5.40, STM32WLxx_DFP.1.2.0

**Describe the bug (skip if none)**
No System Viewer fields while debugging CM0P, so i can check periphery only while using CM4

**Additional context**

Seems like something is wrong with provided files 

**Screenshots**
![MaxFlatline_0-1721744053441](https://github.com/user-attachments/assets/bb3d92dc-4624-44d2-8ef6-1299eec9e81c)
![MaxFlatline_1-1721744102460](https://github.com/user-attachments/assets/bd411d7d-9756-45af-a07e-30d9641a681c)

**Comment by RJMSTM** [comment]
Hello @MaxFlatline,

Thank you for your contribution, but I am unable to reproduce the problem. I conducted a test with

- Nucleo-WL55JC1
- Keil Uvision 5.38, STM32WLxx_DFP.1.2.0

![image](https://github.com/user-attachments/assets/7024213f-8b8a-422e-8e33-d6a02bc16df3)

And everything works well as follows. I am able to see the System Viewer fields.

![image](https://github.com/user-attachments/assets/e4a49f82-9301-4060-a78c-9423073308b4)

Could you please double-check on your side?

Regards,

**Comment by MaxFlatline** [comment]
Hello @RJMSTM 
Yes, i checked on another machine and seems like all is operational.. Extremely strange, i'll close this issue and will try to find what's wrong on my side!

Thank you!

**Comment by MaxFlatline** [comment]
On another machine all is good, will look into it
