### ISSUE TITLE
Support for STM32WL33

### ISSUE THREAD

**Issue by vimalzxc** [STMicroelectronics/STM32CubeWL#91]
How to work with STM32WL33 series MCUs? 
All examples are for STM32WL55 and STM32WL54

**Comment by ALABSTM** [comment]
See also [cmsis_device_wl#2](https://github.com/STMicroelectronics/cmsis_device_wl/issues/2).

**Comment by ALABSTM** [comment]
Hi @vimalzxc,

Please refer to the above-referenced issue to read the answer to your question.

With regards,
