### ISSUE TITLE
Integrating soil sensor into the Lorawan_End_node issue 

### ISSUE THREAD

**Issue by adamlqn** [STMicroelectronics/STM32CubeWL#92]
Setup:

NucleoWL55JC
IDE: 

STM32CubeIDE 1.15.1

Bug & Question:

Hi there, I want to create a LoRaWAN project based on STM32WL with Loarwan_End_node example to read and send data of an implemented soil moisture sensor to a network server, I did a couple of trials regarding this implementation, where I initialised the ADC in the ioc file but it’s not generated within the firmware, while in a normal project is generated correctly.
I modified the firmware by adding the sensor data acquisition and LoRaWAN transmission logic inside the main loop and all the parameters to have the desired output but the end device doesn’t join and the data is not read nor sent to the network server unless the firmware is kept as default.
Any support for my issue would be appreciated.

**Comment by ALABSTM** [comment]
Hi @adamlqn,

Thank you for your interest. As indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeWL/blob/main/CONTRIBUTING.md#3-support-requests-and-questions) file, such support requests should be rather submitted to the **ST Community**.

Your question looks more related to the way your project is generated using the `STM32CubeMX` tool. I then suggest to post your question to [this](https://community.st.com/t5/stm32cubemx-mcus/bd-p/stm32-mcu-cubemx-forum) forum.

Please allow me to close this issue. Thank you for your comprehension and best of luck.

With regards,
